# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cdc33596ea9139f7974cd17adf1e145fd8317f150f2bf2c85a0cba2dbe1498f506425d2ea3427986201e57fdcd7a0fbde7e6afc6735472fb1f839828147b209

test:
  secret_key_base: 6363e953b1d6e892bc03c6ac50ff3eab04eade2c207b9404a4ba0f4d840fe732ebdeb7d226f2e3c7129413a7760360b20cae32d1645761ff5e20e5aa7448a365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
